# Retail Customer shopping Behavior Analysis
## Objective
To analyze customer shopping behavior and identify key factors influencing purchasing decisions, customer engagement, and loyalty.

## Tools Used
- Python (Pandas, NumPy, Seaborn, Matplotlib)
- SQL
- Power BI

1. #importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

2. #loading dataset

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

3. ## Data Understanding

This section explores the structure, size, and quality of the dataset.

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.shape

(3900, 18)

In [5]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [7]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

4. Data Cleaning
   ## Column Name Standardization

Column names were cleaned and standardized by:
- Converting all text to lowercase
- Replacing spaces with underscores
- Removing special characters

This ensures compatibility with Python, SQL, and Power BI.

In [9]:
# Step 1: View original columns
print("Original Columns:")
print(df.columns)

Original Columns:
Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [10]:
# Step 2: Clean column names
df.columns = (
    df.columns
    .str.strip()                          # remove leading/trailing spaces
    .str.lower()                          # convert to lowercase
    .str.replace(' ', '_')                # replace spaces with underscore
    .str.replace('(', '', regex=False)    # remove (
    .str.replace(')', '', regex=False)    # remove )
    .str.replace('-', '_')                # replace hyphens with underscore
)

In [11]:
# Step 3: View cleaned columns
print("\nCleaned Columns:")
print(df.columns)

Cleaned Columns:
Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
# step4 Handle duplicates
df.drop_duplicates(inplace=True)

In [13]:
# step5 Check for inconsistencies in categorical columns
for col in ['customer_id', 'gender', 'category', 'size', 'season', 'subscription_status', 'shipping_type', 'payment_method', 'frequency_of_purchases']:
    print(col, df[col].unique())

customer_id [   1    2    3 ... 3898 3899 3900]
gender ['Male' 'Female']
category ['Clothing' 'Footwear' 'Outerwear' 'Accessories']
size ['L' 'S' 'M' 'XL']
season ['Winter' 'Spring' 'Summer' 'Fall']
subscription_status ['Yes' 'No']
shipping_type ['Express' 'Free Shipping' 'Next Day Air' 'Standard' '2-Day Shipping'
 'Store Pickup']
payment_method ['Venmo' 'Cash' 'Credit Card' 'PayPal' 'Bank Transfer' 'Debit Card']
frequency_of_purchases ['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']

In [14]:
# step6 Convert binary categoricals to 0/1
binary_cols = ['subscription_status', 'discount_applied', 'promo_code_used']
for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

## Feature Engineering: Age Group

Customer ages were segmented into categorical groups (Teen, Young Adult, Adult, Middle Age, Senior) to enable better analysis of purchasing behavior across demographics.

In [15]:
# Define age bins and labels
bins = [0, 18, 30, 45, 60, 100]
labels = ['Teen', 'Young Adult', 'Adult', 'Middle Age', 'Senior']

# Create age_group column
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

# Check result
df[['age', 'age_group']].head()

   age    age_group
0   55   Middle Age
1   19  Young Adult
2   50   Middle Age
3   21  Young Adult
4   45        Adult

In [16]:
# . Create ONE powerful feature: average spend per previous purchase
df['Avg_Spend_Per_Prev'] = df['purchase_amount_usd'] / (df['previous_purchases'] + 1)

In [17]:
# High rating flag (≥4.5)
df['high_rating'] = (df['review_rating'] >= 4.5).astype(int)

In [18]:
# Define mapping from frequency strings to approximate days
frequency_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Quarterly': 91,
    'Every 3 Months': 91,
    'Annually': 365
}

# Create new column
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

# Check result
print(df[['frequency_of_purchases', 'purchase_frequency_days']].drop_duplicates())

   frequency_of_purchases  purchase_frequency_days
0             Fortnightly                       14
2                  Weekly                        7
4                Annually                      365
6               Quarterly                       91
10              Bi-Weekly                       14
15                Monthly                       30
20         Every 3 Months                       91

In [19]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in e:\anaconda\lib\site-packages (9.6.0)

In [20]:
!pip install pymysql sqlalchemy
from sqlalchemy import create_engine
engine= create_engine("mysql+pymysql://root:0728@localhost:3306/customer_shopping_behavior")
print(engine)

Requirement already satisfied: pymysql in e:\anaconda\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in e:\anaconda\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in e:\anaconda\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in e:\anaconda\lib\site-packages (from sqlalchemy) (3.0.1)
Engine(mysql+pymysql://root:***@localhost:3306/customer_shopping_behavior)

In [21]:
df.to_sql(name='customer_shopping_behavior', con=engine, if_exists='replace', index=False)

3900